# Generated by Django 4.2.6 on 2023-10-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UdyanSaathiAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutionmodel',
            name='AQI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollutionmodel',
            name='AQI_Quality',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='pollutionmodel',
            name='CO',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='pollutionmodel',
            name='Checks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollutionmodel',
            name='Date',
            field=models.DateField(default='2023-10-10'),
        ),
        migrations.AddField(
            model_name='pollutionmodel',
            name='NH3',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='pollutionmodel',
            name='NO2',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='pollutionmodel',
            name='OZONE',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='pollutionmodel',
            name='PM10',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='pollutionmodel',
            name='PM25',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='pollutionmodel',
            name='SO2',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='pollutionmodel',
            name='Station',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='pollutionmodel',
            name='City',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='pollutionmodel',
            name='State',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
