# Generated by Django 5.0.6 on 2025-01-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UdyanSaathiAPI', '0003_mlmodel_alter_pollutionmodel_pol_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='mapDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(default=' ', max_length=255)),
                ('City', models.CharField(default=' ', max_length=255)),
                ('Station', models.CharField(default=' ', max_length=500)),
                ('Pol_Date', models.CharField(default=' ', max_length=500)),
                ('AQI', models.IntegerField(default=0)),
                ('AQI_Quality', models.CharField(default=' ', max_length=100)),
                ('Longitude', models.FloatField(default=0, max_length=10)),
                ('Latitude', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StationsCoordinatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Station', models.CharField(default=' ', max_length=500)),
                ('Longitude', models.FloatField(default=0, max_length=10)),
                ('Latitude', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='aqicalendarmodel',
            name='City',
        ),
        migrations.AddField(
            model_name='aqicalendarmodel',
            name='Station',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
